### ISSUE TITLE
Can you add control [ctrl] keyboard key?

### ISSUE THREAD

**Issue by sm64js** [jeremyckahn/keydrown#15]
Can you add control [ctrl] keyboard key?

Or send me a modified Keydrown.min.js with Control key support?

Thanks

**Comment by jeremyckahn** [comment]
Hi @sm64js, it's pretty easy to add left and right ctrl key mappings to [`kd.map.js`](https://github.com/jeremyckahn/keydrown/blob/master/src/kd.map.js), and I could probably add that in the next few days. Before I do that, could you share your use case? If you're looking for modifier key support, Keydrown should already be able to handle that per the [examples here](https://github.com/jeremyckahn/keydrown#example).

**Comment by sm64js** [comment]
haha! Well the my use case is @sm64js 

See sm64js.com and https://github.com/sm64js/sm64js

I've been using your tool for a couple months now! It's great ha! Thank you!

**Comment by jeremyckahn** [comment]
Ah this project is so cool! Nice work! 😃

If you're not looking for modifier key support, then a basic key mapping for ctrl should do the trick. I should have some time to add that within a few days, but if you need it sooner than that, I'd be happy to work with you on a Pull Request!

**Comment by sm64js** [comment]
Let me have a look :)

**Comment by sm64js** [comment]
> it's pretty easy to add left and right ctrl key mappings to kd.map.js

This is all I got to do lol?

**Comment by jeremyckahn** [comment]
> This is all I got to do lol?

Should be!

**Comment by sm64js** [comment]
okay one second.  Will you be able to build it for me afterwards though? the prod minified version? I am not sure the steps for that / tools for that.

**Comment by sm64js** [comment]
nice work making your project extensible

**Comment by jeremyckahn** [comment]
I think this should install everything you need and run the build:

```
npm install
npm run build
```

That should update the files in `dist`. This project is a little out of date so the files in `dist` are tracked in Git. But from there you can test out your new build, commit/push your changes and make a PR so everyone else can get the new functionality too!

**Comment by jeremyckahn** [comment]
> nice work making your project extensible

Ah, thank you! 😁

**Comment by sm64js** [comment]
ahaha, came here to say just kidding (before I saw your posts), I figured out building, I just needed to look!

**Comment by sm64js** [comment]
I made a PR before building... do you want me to submit a new one with the dist files updated?

**Comment by jeremyckahn** [comment]
Nah I got it. I'll take a look at your PR now!

**Comment by jeremyckahn** [comment]
Thanks for the PR @sm64js I ran the `version` script locally and [the `v1.2.8` tag was pushed](https://github.com/jeremyckahn/keydrown/releases/tag/v1.2.8), but it won't publish to NPM for some reason. I'm trying to figure out why that is.

In any case you can use the version on Github if you want to use it right now. Thanks again and great work on your project! 🙂

**Comment by sm64js** [comment]
Excellent! I just updated my project with this, someone was asking for support for the ctrl button

**Comment by jeremyckahn** [comment]
Somehow I was silently logged out of NPM on my machine. I logged in and just published to NPM: https://www.npmjs.com/package/keydrown/v/1.2.8

I'm glad Keydrown is working well for you! It's super motivating to see it in awesome projects like this! 😁

**Comment by sm64js** [comment]
Do you have a list of projects somewhere that use keydrown, that I should add myself to the list?

**Comment by jeremyckahn** [comment]
I do! https://github.com/jeremyckahn/keydrown

Feel free to make a PR, otherwise I can add your project a little later today. :)
