### ISSUE TITLE
Event should bind to specific key and not the key's character

### ISSUE THREAD

**Issue by varemenos** [jeremyckahn/keydrown#2]
Lets say for example that I have 2 keyboard layouts selected for my OS.
1. US
2. Greek

If I listen for the keydown event for the character `Q` it will work for the US layout but won't for the Greek character assigned in the same key-location as `Q`.

**Comment by srgpqt** [comment]
This is possible now with recent versions of Chrome and Firefox, using they `code` property of the keyboard event object.

https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code
https://w3c.github.io/uievents/#widl-KeyboardEvent-code

**Comment by jeremyckahn** [comment]
@srgpqt Very interesting, thanks for sharing this spec!  I don't have any plans to implement this functionality, but I would be open to a Pull Request to add support for it.
