### ISSUE TITLE
No Way To Determine Delta Time

### ISSUE THREAD

**Issue by jcmiller11** [jeremyckahn/keydrown#9]
For keydrown to be more useful to any javascript game developers, within the key event functions there must be some way to find out how much time has elapsed since the last time kd.tick() was called or a tick occurred.

**Comment by jeremyckahn** [comment]
Hi @jcmiller11, thanks for filing a ticket.  That sounds like a good idea!  I'll try to add that feature in the next few days.  Feel free to make a PR if you need it sooner, though.

**Comment by jeremyckahn** [comment]
Update: Actually implementing this feature is really straightforward, but I'm blocked on being able to actually build and release the change.  Some of the build and release process dependencies have been broken by recent versions of NPM, so I need to fix those before I can address this issue (or any others).  It's not a terribly difficult thing to fix, just time-consuming.  In any case, I hope to have a PR for review within the next week or so.

**Comment by jeremyckahn** [comment]
@jcmiller11, please review the PR that addresses this: https://github.com/jeremyckahn/keydrown/pull/10

**Comment by jcmiller11** [comment]
Cool, as a totally contrived example, here's a base for starting a super efficient html5 game engine based on pixi.js and keydrown https://jsfiddle.net/104m06cq/

**Comment by jeremyckahn** [comment]
Oh nice!  I think a few people have used Keydrown in combination with Pixi.  I'm glad they work so well together!
